"""add child_profiles table and link to toddlers

Revision ID: 5077fff58f65
Revises: 1a88434c3fad
Create Date: 2025-07-08 21:21:17.570478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5077fff58f65'
down_revision: Union[str, None] = '1a88434c3fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    op.create_index(op.f('ix_child_profiles_id'), 'child_profiles', ['id'], unique=False)
    op.add_column('toddlers', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.alter_column('toddlers', 'weight_kg',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('toddlers', 'height_cm',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_toddlers_name', table_name='toddlers')
    op.drop_index('nik', table_name='toddlers')
    op.drop_constraint('toddlers_ibfk_1', 'toddlers', type_='foreignkey')
    op.create_foreign_key(None, 'toddlers', 'child_profiles', ['profile_id'], ['id'])
    op.drop_column('toddlers', 'nik')
    op.drop_column('toddlers', 'tanggal_lahir')
    op.drop_column('toddlers', 'tempat_lahir')
    op.drop_column('toddlers', 'user_id')
    op.drop_column('toddlers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toddlers', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('toddlers', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('toddlers', sa.Column('tempat_lahir', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('toddlers', sa.Column('tanggal_lahir', sa.DATE(), nullable=True))
    op.add_column('toddlers', sa.Column('nik', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'toddlers', type_='foreignkey')
    op.create_foreign_key('toddlers_ibfk_1', 'toddlers', 'users', ['user_id'], ['id'])
    op.create_index('nik', 'toddlers', ['nik'], unique=True)
    op.create_index('ix_toddlers_name', 'toddlers', ['name'], unique=False)
    op.alter_column('toddlers', 'height_cm',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('toddlers', 'weight_kg',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_column('toddlers', 'profile_id')
    op.drop_index(op.f('ix_child_profiles_id'), table_name='child_profiles')
    op.drop_table('child_profiles')
    # ### end Alembic commands ###
