"""add rt rw field

Revision ID: 66ec77843e64
Revises: e15901cbcfc5
Create Date: 2025-07-08 19:56:40.604900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ec77843e64'
down_revision: Union[str, None] = 'e15901cbcfc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rt', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('rw', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rw')
    op.drop_column('users', 'rt')
    # ### end Alembic commands ###
