"""Add Predicted Col and source for information

Revision ID: e15901cbcfc5
Revises: b9df5fa746f9
Create Date: 2025-05-20 20:59:46.934608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e15901cbcfc5'
down_revision: Union[str, None] = 'b9df5fa746f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('toddlers', sa.Column('predicted', sa.String(length=255), nullable=True))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('toddlers', 'predicted')
    op.drop_column('information', 'source')
    # ### end Alembic commands ###
