"""Add image_url, category column to information & Toddler column revised

Revision ID: eca303fd923a
Revises: a3c8df4d7311
Create Date: 2025-05-04 19:43:44.133917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eca303fd923a'
down_revision: Union[str, None] = 'a3c8df4d7311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('information', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_column('information', 'img_filename')
    op.add_column('toddlers', sa.Column('prediction_result', sa.String(length=100), nullable=True))
    op.alter_column('toddlers', 'gender',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint('toddlers_ibfk_1', 'toddlers', type_='foreignkey')
    op.drop_column('toddlers', 'prediction')
    op.drop_column('toddlers', 'user_id')
    op.drop_column('toddlers', 'probability')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toddlers', sa.Column('probability', mysql.FLOAT(), nullable=False))
    op.add_column('toddlers', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('toddlers', sa.Column('prediction', mysql.VARCHAR(length=100), nullable=False))
    op.create_foreign_key('toddlers_ibfk_1', 'toddlers', 'users', ['user_id'], ['id'])
    op.alter_column('toddlers', 'gender',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('toddlers', 'prediction_result')
    op.add_column('information', sa.Column('img_filename', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('information', 'image_url')
    op.drop_column('information', 'category')
    # ### end Alembic commands ###
